[package]
name = "monitord"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.2.22", features = ["derive"] }
clap-verbosity-flag = "1.0.1"
configparser = "3.0.2"
env_logger = "0.9"
log = "0.4"
