name: Crate Publish

on:
  release:
    types: created

jobs:
  publish:
    name: crates.io publish ${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Publish
        uses: actions-rs/cargo@v1
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: publish
          args: --verbose
